flags:
  alsa-core:
    pkgconfig: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- X11-xft-0.3.1
- alsa-core-0.5.0.1
- alsa-mixer-0.2.0.3
- libmpd-0.9.0.6
- xmonad-contrib-0.13
- xmonad-0.13
resolver: lts-8.4
